spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/MY-D
    driver-class-name: org.h2.Driver
    username: sa

  ### H2 DataBase ###
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true