# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env: 
        SECRET: ${{secrets.SECRET}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      
  CD:
    runs-on: ubuntu-latest
    needs: CI
    env: 
        SECRET: ${{secrets.SECRET}}
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: grant privileges to gradlew
      run: chmod +x gradlew
    
    - name: run build
      run: ./gradlew build 
    
    - name : Docker Login
      uses: docker/login-action@v1.10.0
      with:
        name: joungeun/myd
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Build Docker Image
      run: docker build -t joungeun/myd .
      
    - name: Upload to DockerHub
      run: docker push joungeun/myd
    
